Description: Group for ACE training (through NIAID/NIH)
Department: Bioinformatics and Computational Biosciences Branch (BCBB)
FieldOfScience: Training
Organization: NIAID/NIH
PIName: Mariam Quiñones

Sponsor:
  CampusGrid:
    Name: OSG Connect
FieldOfScienceID: "30.3001"
DangerousCalculated_BroadFieldOfScience: Multidisciplinary/ interdisciplinary sciences
DangerousCalculated_MajorFieldOfScience: Multidisciplinary/ interdisciplinary sciences, other
DangerousCalculated_DetailedFieldOfScience: Computational science and engineering
