# LongName is the expanded name of the site
LongName: University of Hawaii Institute for Astronomy Hilo
# Description is a brief description of your site
Description: Institute for Astronomy at the University of Hawaii at Hilo Research Park

# If you have an up-to-date local git clone, fill ID with the output from `bin/next_site_id`
# Otherwise, leave it blank and we will fill in the appropriate value for you.
ID: 10342

# AddressLine1 is the street address of the site
AddressLine1: 640 N Aohoku Pl
### AddressLine2 (optional) is the second line of the street address
# AddressLine2: Room 101
# City is the city the site is located in
City: Hilo

# Country is the country the site is located in
Country: United States
### State (optional) is the state or province the site is located in
State: Hawaii
### Zipcode (optional) is the zipcode/postal code of the site
# Zipcode: "01234"

# Latitude is the latitude of the site (positive values are in the northern hemisphere)
Latitude: 19.703
# Longitude is the longitude of the site (positive values are in the eastern hemisphere)
Longitude: -155.091
