LongName: University of Wisconsin Milwaukee
Description: The University of Wisconsin Milwaukee UWM-NEMO cluster 

AddressLine1: Milwaukee, WI 53211, Stati Uniti
City: Milwaukee

Country: United States
State: Wisconsin
Zipcode: "53211"

Latitude: 43.038902
Longitude: -87.906471
