Description: Institute for Cosmic Ray Research, University of Tokyo
AddressLine1: 5-1-5 Kashiwa-no-Ha
City: Kashiwa
State: Chiba Prefecture
Country: Japan
Zipcode: '277-8582'
Latitude: 35.90641
Longitude: 139.93761
