LongName: West Texas A&M University 
Description: West Texas A&M University Cluster

ID: 10305

AddressLine1: 
City: Canyon
Country: USA
State: TX
Zipcode: "79016"

# Latitude is the latitude of the site (positive values are in the northern hemisphere)
Latitude: 34.980868
# Longitude is the longitude of the site (positive values are in the eastern hemisphere)
Longitude: -101.915859
