LongName: Riga Technical University CMS Tier-2
Description: CMS Tier-2 site hosted by the Latvia CMS Tier-2 Federation in Riga Technical University

AddressLine1: 6A Kipsalas Street
City: Riga
Country: Latvia
### State (optional) is the state or province the site is located in
# State: Wisconsin
Zipcode: "LV-1048"

Latitude: 56.9539
Longitude: 23.8959
