LongName: Compute Canada Cedar Cluster
Description: Cedar is a heterogeneous cluster suitable for a variety of workloads; it is located at Simon Fraser University.
ID: 10281
AddressLine1: 8888 University Drive
City: Burnaby
Country: Canada
State: BC
Zipcode: "V5A 1S66"
Latitude: 49.278639393188136
Longitude: -122.91726450229353
