# LongName is the expanded name of the site
LongName: Albert Einstein Institute
# Description is a brief description of your site
Description: Albert Einstein Institute

# AddressLine1 is the street address of the site
AddressLine1: Am Mühlenberg 1
### AddressLine2 (optional) is the second line of the street address
# AddressLine2: Room 101
# City is the city the site is located in
City: Potsdam

# Country is the country the site is located in
Country: Germany
### State (optional) is the state or province the site is located in
# State: Wisconsin
### Zipcode (optional) is the zipcode/postal code of the site
Zipcode: D-14476

# Latitude is the latitude of the site (positive values are in the northern hemisphere)
Latitude: 52.416389
# Longitude is the longitude of the site (positive values are in the eastern hemisphere)
Longitude: 12.969167
