---
LongName: Global Laboratory for Energy Asset Management and Manufacturing
Description: >-
  GLEAMM advances demonstration of new university innovations and
  accelerates commercialization of next-generation industry technologies
  for enhancing the existing electricity grid towards a smart, secure
  and resilient energy system.
ID: 10340
AddressLine1: 2500 Broadway St
City: Lubbock
State: Texas
Country: United States
Zipcode: "79409"
Latitude: 33.59
Longitude: -101.81
