LongName: Old Dominion University
Description: Old Dominion University Ubuntu Cluster

ID: 10303

AddressLine1: 
City: Norfolk
Country: USA
State: VA
Zipcode: "23529"

# Latitude is the latitude of the site (positive values are in the northern hemisphere)
Latitude: 36.8857071961869
# Longitude is the longitude of the site (positive values are in the eastern hemisphere)
Longitude: -76.30770625583946
