AddressLine1: 940 N McCarthy Blvd
AddressLine2: 
City: Milpitas
Country: United States
Description: Hewlett Packard Labs
Latitude: 37.43
LongName: Hewlett Packard Labs
Longitude: -121.923
State: CA
Zipcode: 95035
