name: Check Project FOS Precision
on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9.15
          cache: 'pip' # caching pip dependencies
      - run: pip install -r ./.github/scripts/check_project_fos_precision/requirements.txt
      - run: python ./.github/scripts/check_project_fos_precision/main.py